<div id="menukar-header">
  <a href="/">
    <img src="/images/icones/grand/home.png" title="Home" class="button-header">
    <span class="text-header">
      Home
    </span>
  </a>
  <div class="Menukar-logo">
    Menukar - 42 <span>Béta</span>
  </div>
  <div id="menukar-header-option">
    <a href="#" class="button-option">
      <img src="/images/icones/grand/chat.png" title="Chat" class="button-header">
    </a>
    <a href="#" class="button-option">
      <img src="/images/icones/grand/favoris.png" title="Favoris" class="button-header">
    </a>
    <a href="/param" class="button-option">
      <img src="/images/icones/grand/param.png" title="Paramètres" class="button-header">
    </a>
  </div>
</div>
