<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Menukar - 42</title>
    <?php echo $this->headLink()->appendStylesheet('/blueprint/src/reset.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/blueprint/src/grid.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/blueprint/src/forms.css') ?>
    <?php echo $this->headLink()->appendStylesheet('/turbine/css.php?files=css3/main.cssp') ?>
    <script type="text/javascript" src="http://www.lqdn.fr/cornerpopup/cornerpopup.js"></script>
  </head>
  <body>
    <script src="/js/jquery/1.4.4/jquery.min.js"></script>
    <script src="/js/jquery/jquery.validate.min.js"></script>
    <div class="container">
      <?php echo $this->partial('partials/menu.phtml', null); ?>
      <div id="menukar-content">
        <div id="menukar-fil">
          <div class="header-fil">
            <img src="/images/icones/grand/suppr.png" title="Home"/ class="logo-menu">
            <a href="http://fr.wikipedia.org/wiki/H2G2_:_le_Guide_du_voyageur_galactique" target="_blank"><span>Don't Panic</span></a>
          </div>
          <div class="clear"></div>
          <div class="content-fil">
            <div class="body-fil error-page">
              <?php echo $this->layout()->content; ?>
            </div>
          </div>
          <div class="clear"></div>
          <div class="footer-fil"></div>
        </div>
      </div>
    </div>
    <script src="/js/menukar/menukar.js"></script>
    <script src="/js/menukar/menukarApi.js"></script>
    
  </body>
</html>

