<div class="error-msg">
  <h2><?php echo "Erreur ".$this->code ?></h2>
  <p>
    <?php echo $this->message ?>
  </p>
</div>

<?php if (isset($this->exception)): ?>
<hr/>
<div class="debug-error">
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <p>
    <pre class="notice"><?php echo $this->exception->getTraceAsString() ?>
    </pre>
  </p>

  <h3>Request Parameters:</h3>
  <pre class="notice"><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
</div>
<?php endif ?>
